stages:
  - lint
  - package

lint: 
  stage: lint
  image: pipelinecomponents/luacheck:latest
  script:
    - luacheck .
package:
  stage: package
  script: 
    - apt-get update -y
    - apt-get install -y zip
    - zip -r AkistosCraftCompendium.zip AkistosCraftCompendium.toc Namespace.lua Controller/ Model/ View/
  artifacts: 
    paths:
      - AkistosCraftCompendium.zip