stages:
  - lint
  - test
  - package

lint:
  stage: lint
  image: public.ecr.aws/docker/library/alpine:3
  before_script:
    - apk add --no-cache luacheck
  script:
    - luacheck .

test:
  stage: test
  image: public.ecr.aws/docker/library/alpine:3
  before_script:
    - apk add --no-cache lua5.4
  script:
    - lua5.4 tests/test_tracker.lua

package:
  stage: package
  image: public.ecr.aws/docker/library/alpine:3
  before_script:
    - apk add --no-cache zip
  script:
    - zip -r AkistosCraftCompendium.zip AkistosCraftCompendium.toc Namespace.lua Controller/ Model/ View/
  artifacts:
    paths:
      - AkistosCraftCompendium.zip
