-- CookingExtras.lua — hand-authored entries not generated by the build pipeline.
-- Appended after Cooking.lua so npm run build does not overwrite them.
ACC_Data = ACC_Data or {}
ACC_Data["Cooking"] = ACC_Data["Cooking"] or {}

table.insert(ACC_Data["Cooking"], {
    _book = true,
    name = "Expert Cooking",
    skill = 150,
    bookName = "Expert Cookbook",
    bookItemId = 16072,
    vendors = {
        { name = "Shandrina",          zone = "Ashenvale",       faction = "alliance" },
        { name = "Malygen",            zone = "Felwood",          faction = "alliance" },
        { name = "Vivianna",           zone = "Dustwallow Marsh", faction = "alliance" },
        { name = "Wulan",              zone = "Desolace",         faction = "horde" },
        { name = "Sheendra Tallgrass", zone = "Feralas",          faction = "horde" },
        { name = "Himmik",             zone = "Winterspring" },
    },
})

table.insert(ACC_Data["Cooking"], {
    _quest = true,
    name = "Artisan Cooking",
    skill = 225,
    questName  = "Clamlette Surprise",
    questLevel = 45,
    questGivers = {
        { name = "Dirge Quixx", zone = "Tanaris", questId = 6610 },
    },
})
