-- FirstAidExtras.lua — hand-authored entries not generated by the build pipeline.
-- Appended after FirstAid.lua so npm run build does not overwrite them.
ACC_Data = ACC_Data or {}
ACC_Data["First Aid"] = ACC_Data["First Aid"] or {}

table.insert(ACC_Data["First Aid"], {
    _book = true,
    name = "Expert First Aid",
    skill = 125,
    bookName = "Expert First Aid - Under Wraps",
    bookItemId = 16084,
    vendors = {
        { name = "Deneb Walker",    zone = "Arathi Highlands", faction = "alliance" },
        { name = "Balai Lok'Wein", zone = "Dustwallow Marsh", faction = "horde" },
    },
})

table.insert(ACC_Data["First Aid"], {
    _quest = true,
    name = "Artisan First Aid",
    skill = 225,
    questName  = "Triage",
    questLevel = 45,
    questGivers = {
        { name = "Doctor Gustaf VanHowzen", zone = "Theramore Isle",   faction = "alliance", questId = 6624 },
        { name = "Doctor Gregory Victor",   zone = "Arathi Highlands", faction = "horde",    questId = 6622 },
    },
})
